### ISSUE TITLE
Q: what does "Object has already been returned to this pool or is invalid" mean in `lock`

### ISSUE THREAD

**Issue by podholadavid** [himadieievsv/redpulsar#71]
Hi, 

great library, thanks a ton for that!

What I am observing in the production environment is, getting this exception

```
Failsafe suppressed exception.
java.lang.IllegalStateException: Object has already been returned to this pool or is invalid
at org.apache.commons.pool2.impl.BaseGenericObjectPool.markReturningState(BaseGenericObjectPool.java:1251)
at org.apache.commons.pool2.impl.GenericObjectPool.returnObject(GenericObjectPool.java:1029)
at io.lettuce.core.support.ConnectionPoolSupport$1.returnObject(ConnectionPoolSupport.java:129)
at io.lettuce.core.support.ConnectionPoolSupport$1.returnObject(ConnectionPoolSupport.java:117)
at com.himadieiev.redpulsar.lettuce.abstracts.AbstractLettucePooled.executeSync(AbstractLettucePooled.kt:81)
at com.himadieiev.redpulsar.lettuce.LettucePooled.sync(LettucePooled.kt:37)
at com.himadieiev.redpulsar.lettuce.locks.backends.LettuceLocksBackend.setLock(LettuceLocksBackend.kt:21)
at com.himadieiev.redpulsar.core.locks.abstracts.AbstractLock.lockInstance(AbstractLock.kt:27)
at com.himadieiev.redpulsar.core.locks.SimplifiedMutex.lock(SimplifiedMutex.kt:39)

```

when trying to `lock`. Any idea what that can mean and how should I fix that?

Thanks in advance!

**Comment by himadieievsv** [comment]
Hi there! Thanks for stoping by Redpulsar. 
Let me get back to you after some investigation. 
Can you also share your use case and connection pool config?

**Comment by podholadavid** [comment]
The use case is to run a SimplifiedMutex to stop other pods from executing a computing heavy method.
I am not seeing any pool configuration in the code so I assume we use some defaults.

**Comment by himadieievsv** [comment]
Since ObjectPool manages connection in the pool, best thing to do it let it manage.
I attempted to handle IllegalStateException that is caused by borrowed object is not in correct state in [v1.3.2](https://github.com/himadieievsv/redpulsar/releases/tag/v1.3.2) .

Please try using the newest lib: `implementation("com.himadieiev:redpulsar-lettuce:1.3.2")`

I also recommend to set pool size, by default it have only 8 connections. Here is example in kotlin how to do it:
https://github.com/himadieievsv/distributed-locks/blob/26212f357310e028740115fd962f3a9aa4e20be0/redpulsar-lettuce/src/test/kotlin/TestCommons.kt#L49-L56 
Java example is similar, just use setters instead of `apply()`

**Comment by podholadavid** [comment]
Thanks a lot, really impressed.
We will both try the new version and actually set the pool size.

**Comment by podholadavid** [comment]
Just wanted to follow-up here, we use the new version, works fine, was not able to update the pool size tho 🙈

**Comment by himadieievsv** [comment]
Great news!
For pool size you can create new issue and we discuss it there.
